#!/usr/bin/env node
/**
 * Copies the third-party libraries and font files the template uses out of
 * node_modules and into assets/, so the template runs with no network at all.
 *
 * Buyers never need to run this — assets/vendor and assets/fonts ship with the
 * template. It exists so those files can be regenerated when a dependency is
 * upgraded.
 *
 *   npm install && node tools/vendor.js
 */

"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const NM = path.join(ROOT, "node_modules");
const VENDOR = path.join(ROOT, "assets", "vendor");
const FONTS = path.join(ROOT, "assets", "fonts");

fs.mkdirSync(VENDOR, { recursive: true });
fs.mkdirSync(FONTS, { recursive: true });

/** Copies src → dest, returning false rather than throwing when src is absent. */
function copy(from, to) {
  if (!fs.existsSync(from)) return false;
  fs.copyFileSync(from, to);
  return true;
}

/** Finds the first candidate that exists, so a layout change doesn't break us. */
function firstOf(candidates) {
  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  return null;
}

/* ------------------------------------------------------------------ libs -- */

const LIBS = [
  {
    name: "bootstrap.min.css",
    from: [path.join(NM, "bootstrap/dist/css/bootstrap.min.css")],
  },
  {
    name: "bootstrap.bundle.min.js",
    from: [path.join(NM, "bootstrap/dist/js/bootstrap.bundle.min.js")],
  },
  {
    name: "swiper-bundle.min.css",
    from: [path.join(NM, "swiper/swiper-bundle.min.css")],
  },
  {
    name: "swiper-bundle.min.js",
    from: [path.join(NM, "swiper/swiper-bundle.min.js")],
  },
  {
    name: "lenis.min.js",
    from: [
      path.join(NM, "lenis/dist/lenis.min.js"),
      path.join(NM, "lenis/dist/lenis.js"),
      path.join(NM, "lenis/dist/lenis.umd.js"),
      path.join(NM, "lenis/dist/lenis.umd.min.js"),
    ],
  },
  {
    name: "lucide.min.js",
    from: [path.join(NM, "lucide/dist/umd/lucide.min.js")],
  },
];

let libCount = 0;
LIBS.forEach((lib) => {
  const candidates = Array.isArray(lib.from) ? lib.from : Object.values(lib.from);
  const src = firstOf(candidates.filter((c) => typeof c === "string"));
  if (src && copy(src, path.join(VENDOR, lib.name))) {
    libCount++;
    process.stdout.write("  vendor  " + lib.name + "\n");
  } else {
    process.stdout.write("  MISSING " + lib.name + "\n");
    process.exitCode = 1;
  }
});

/* ----------------------------------------------------------------- fonts -- */

/** family → [package, weights]. Latin subset only; add more if you need them. */
const FAMILIES = [
  { css: "Syne", pkg: "syne", file: "syne", weights: [600, 700, 800] },
  { css: "Inter", pkg: "inter", file: "inter", weights: [400, 500, 600] },
  {
    css: "JetBrains Mono",
    pkg: "jetbrains-mono",
    file: "jetbrains-mono",
    weights: [400, 500],
  },
];

let face = "";
let fontCount = 0;

FAMILIES.forEach((fam) => {
  fam.weights.forEach((w) => {
    const name = `${fam.file}-latin-${w}-normal.woff2`;
    const src = path.join(NM, "@fontsource", fam.pkg, "files", name);

    if (!copy(src, path.join(FONTS, name))) {
      process.stdout.write("  MISSING font " + name + "\n");
      process.exitCode = 1;
      return;
    }

    fontCount++;
    face +=
      `@font-face {\n` +
      `  font-family: "${fam.css}";\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${w};\n` +
      `  font-display: swap;\n` +
      `  src: url("../fonts/${name}") format("woff2");\n` +
      `  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC,\n` +
      `    U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F,\n` +
      `    U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n` +
      `}\n\n`;
  });
});

const header =
  "/* Self-hosted fonts — generated by tools/vendor.js, do not edit by hand.\n" +
  "   Syne, Inter and JetBrains Mono are licensed under the SIL Open Font\n" +
  "   License, which permits bundling and redistribution. */\n\n";

fs.writeFileSync(path.join(ROOT, "assets", "css", "fonts.css"), header + face);

process.stdout.write(
  `\n${libCount}/${LIBS.length} libraries, ${fontCount} font files vendored\n`
);
